# Generated by Django 5.1.1 on 2024-10-01 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_video_url_video_thumbnail_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='video',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='api.video'),
            preserve_default=False,
        ),
    ]
