# Generated by Django 5.1.1 on 2024-10-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comments_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='user',
            new_name='uploaded_by',
        ),
    ]
