# Generated by Django 5.1.1 on 2024-10-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_video_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
    ]
